/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EipSetupDependencies {
    }
    interface MyComponent {
        "open": () => Promise<void>;
    }
}
declare global {
    interface HTMLEipSetupDependenciesElement extends Components.EipSetupDependencies, HTMLStencilElement {
    }
    var HTMLEipSetupDependenciesElement: {
        prototype: HTMLEipSetupDependenciesElement;
        new (): HTMLEipSetupDependenciesElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "eip-setup-dependencies": HTMLEipSetupDependenciesElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface EipSetupDependencies {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "eip-setup-dependencies": EipSetupDependencies;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eip-setup-dependencies": LocalJSX.EipSetupDependencies & JSXBase.HTMLAttributes<HTMLEipSetupDependenciesElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
