/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EipSearchDialog {
        "open": () => Promise<void>;
    }
    interface EipSetupDependencies {
    }
}
declare global {
    interface HTMLEipSearchDialogElement extends Components.EipSearchDialog, HTMLStencilElement {
    }
    var HTMLEipSearchDialogElement: {
        prototype: HTMLEipSearchDialogElement;
        new (): HTMLEipSearchDialogElement;
    };
    interface HTMLEipSetupDependenciesElement extends Components.EipSetupDependencies, HTMLStencilElement {
    }
    var HTMLEipSetupDependenciesElement: {
        prototype: HTMLEipSetupDependenciesElement;
        new (): HTMLEipSetupDependenciesElement;
    };
    interface HTMLElementTagNameMap {
        "eip-search-dialog": HTMLEipSearchDialogElement;
        "eip-setup-dependencies": HTMLEipSetupDependenciesElement;
    }
}
declare namespace LocalJSX {
    interface EipSearchDialog {
    }
    interface EipSetupDependencies {
    }
    interface IntrinsicElements {
        "eip-search-dialog": EipSearchDialog;
        "eip-setup-dependencies": EipSetupDependencies;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eip-search-dialog": LocalJSX.EipSearchDialog & JSXBase.HTMLAttributes<HTMLEipSearchDialogElement>;
            "eip-setup-dependencies": LocalJSX.EipSetupDependencies & JSXBase.HTMLAttributes<HTMLEipSetupDependenciesElement>;
        }
    }
}
