/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IntlResources, Localize } from "./interfaces/intl";
import { Formats } from "intl-messageformat";
export namespace Components {
    interface EipIntl {
        "format": Partial<Formats>;
        "language": string;
        "resources": IntlResources;
        "useKeyIfMissing": boolean;
    }
    interface EipSearchDialog {
        "open": () => Promise<void>;
    }
    interface EipSetupDependencies {
    }
}
declare global {
    interface HTMLEipIntlElement extends Components.EipIntl, HTMLStencilElement {
    }
    var HTMLEipIntlElement: {
        prototype: HTMLEipIntlElement;
        new (): HTMLEipIntlElement;
    };
    interface HTMLEipSearchDialogElement extends Components.EipSearchDialog, HTMLStencilElement {
    }
    var HTMLEipSearchDialogElement: {
        prototype: HTMLEipSearchDialogElement;
        new (): HTMLEipSearchDialogElement;
    };
    interface HTMLEipSetupDependenciesElement extends Components.EipSetupDependencies, HTMLStencilElement {
    }
    var HTMLEipSetupDependenciesElement: {
        prototype: HTMLEipSetupDependenciesElement;
        new (): HTMLEipSetupDependenciesElement;
    };
    interface HTMLElementTagNameMap {
        "eip-intl": HTMLEipIntlElement;
        "eip-search-dialog": HTMLEipSearchDialogElement;
        "eip-setup-dependencies": HTMLEipSetupDependenciesElement;
    }
}
declare namespace LocalJSX {
    interface EipIntl {
        "format"?: Partial<Formats>;
        "language"?: string;
        "onLocalize"?: (event: CustomEvent<Localize>) => void;
        "resources"?: IntlResources;
        "useKeyIfMissing"?: boolean;
    }
    interface EipSearchDialog {
    }
    interface EipSetupDependencies {
    }
    interface IntrinsicElements {
        "eip-intl": EipIntl;
        "eip-search-dialog": EipSearchDialog;
        "eip-setup-dependencies": EipSetupDependencies;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eip-intl": LocalJSX.EipIntl & JSXBase.HTMLAttributes<HTMLEipIntlElement>;
            "eip-search-dialog": LocalJSX.EipSearchDialog & JSXBase.HTMLAttributes<HTMLEipSearchDialogElement>;
            "eip-setup-dependencies": LocalJSX.EipSetupDependencies & JSXBase.HTMLAttributes<HTMLEipSetupDependenciesElement>;
        }
    }
}
